changesets/action

- README.md
As you can see [in this action I have on one of my repos](https://github.com/ChristopherBiscardi/gatsby-plugins/blob/a6368670fd98c0950036d7ddab920fccbf3dce89/.github/workflows/npmpublish.yml#L8-L17), yarn is already installed by the `setup-node` action and so doesn't need to be re-installed
> remove install of yarn from action (because it is already installed)

- index.ts
Mainly because I had to DDG for the action name to get back to it
> Include a link back to the README for folks to read

- .changeset/two-dolls-promise.md
- README.md
- action.yml
- package.json
- src/index.ts
- yarn.lock
Fixes #126, alternative solution to #127
Instead of implementing git commit signing into the action, we could allow an input option to disable the `setupUser` function so that consumers can use their own git user to create commits in this action.
- Add `setupGitUser` boolean input option
- Updated `@actions/core` to be able to use `getBooleanInput`
- Default to `true`
- Don't run `gitUtils.setupUser()` if `setupGitUser` is `false`
- Update docs
> custom git user input option

- .changeset/fresh-frogs-knock.md
- action.yml
- src/index.ts
- src/run.ts
Reopen https://github.com/changesets/action/pull/108 due to change in base branch to `main`
> allow skipping creation of Github releases

- README.md
This should limit possible race conditions as only a single run of a workflow can be active at any given moment thanks to this setting:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
> Add `concurrency` option to the exampels in the README

- .changeset/old-socks-unite.md
- src/index.ts
This PR applies `cwd` before setting the git user name and email. Without this change, the git setup commands are run in `$GITHUB_WORKSPACE`, which will fail if `$GITHUB_WORKSPACE` is not a git repo.
Fixes https://github.com/changesets/action/issues/159.
> Change directory to `cwd` before running git user setup.

- .changeset/long-mayflies-yell.md
- action.yml
- src/index.ts
- src/run.test.ts
- src/run.ts
Closes: https://github.com/changesets/action/issues/82
> feat: set pullRequestNumber as action output

- README.md
Changesets automatically deepens a shallow clone as necessary,
so we don't need to recommend a complete deep clone in order
for changesets to work.
Fixes: #97
> Remove suggestions of using `fetch-depth: 0`

- .changeset/lucky-pans-thank.md
- src/__snapshots__/run.test.ts.snap
- src/run.test.ts
- src/run.ts
I had an issue today where the PR body exceeded a size limit.
This prevents the PR to be created.
To fix that we can truncate the message if we detect it's too long.
Let me know what you think and if I need to add a test for this use case.
This is how the truncated message in the PR looks like:
> fix: github PR body max length

- README.md
The `email=my@email.com` line isn't necessary. It doesn't seem to be a real configuration option and as far as I can tell npm ignores it. 
fixes #185
> remove unnecessary config from README

- README.md
- Adds reference to the `baseBranch` config in the Changesets docs
- Updates all references in examples to `main` instead of `master`
- [`main` is now the default branch](https://github.com/github/renaming) in new GitHub projects
- This change aligns with the comment in the `baseBranch` section of Changesets docs
> chore(docs): Update README to reference baseBranch, use "main" as default in examples

- .changeset/three-needles-protect.md
- src/index.ts
Fixes #205.
Note that this maintains the previous behavior that if there are any
changesets (even empty ones), the action does not publish packages.
> Don't create a PR if all changesets are empty

- .github/workflows/ci.yml
- .github/workflows/version-or-publish.yml
- action.yml
- package.json
Bumps the action to use node16
> Use node16 in actions

- .changeset/sharp-pens-matter.md
- src/run.ts
Fixes https://github.com/changesets/action/issues/227 by adding the required `is:pull-request` filter to the search query. This will allow users to use user-owned PATs instead of the default `GITHUB_TOKEN`.
> Add `is:pull-request` to search query when looking for existing PR

- .changeset/rotten-carrots-pump.md
- package.json
- src/run.ts
- yarn.lock
Adds the octokit plugin for throttling / rate-limiting to fix the problem where action runs get blocked with a 403 error[1].
The `github.getOctokit`[2] function accepts a list of plugins, so this passes in the `throttling` plugin[3] to be hooked into the octokit instance.
It also needs some configuration to setup the `throttle` mechanisms, passed in to the `getOctokit` function.
[1]: https://github.com/changesets/action/issues/192
[2]: https://github.com/actions/toolkit/blob/main/packages/github/src/github.ts#LL18C40-L18C40
[3]: https://github.com/octokit/plugin-throttling.js
closes https://github.com/changesets/action/issues/192
> fix: prevent hitting github secondary rate limits

- .changeset/blue-hornets-marry.md
- src/index.ts
- src/run.ts
Use logging from `@actions/core`[1] over console-based logging recommended by the javascript action template[2].
[1]: https://github.com/actions/toolkit/tree/main/packages/core#logging
[2]: https://github.com/actions/javascript-action/blob/main/index.js
> chore: migrate to logging from @actions/core

- .changeset/new-worms-knock.md
- src/run.test.ts
- src/run.ts
Related to #192.
This adds the throttling plugin to other usages of octokit that were overlooked the first time around.
cc: @Andarist
> fix: use throttling-wired octokit everywhere

- .changeset/kind-sheep-grab.md
- .github/workflows/ci.yml
- .github/workflows/version-or-publish.yml
- README.md
- action.yml
- package.json
- yarn.lock
Hi. Node.js 16 actions are deprecated now.
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> chore: bump nodejs from 16 to 20

- .github/workflows/ci.yml
- .github/workflows/version-or-publish.yml
Fixes [existing warnings](https://github.com/changesets/action/actions/runs/8336499280)
```console
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2, actions/setup-node@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
> Use latest versions of checkout and setup-node actions

- .changeset/clean-bees-count.md
- .changeset/green-eels-appear.md
- src/run.test.ts
- src/run.ts
To reduce the amount of rate-limit that we use, switch to a cheaper API for determining whether an existing PR exists for a given branch.
This should avoid hitting the secondary rate limits as much
Context: https://github.com/changesets/action/pull/391#issuecomment-2309938444
See also #192 
Tested here:
* https://github.com/s0/changesets-action/pull/8
* workflow run (notice no rate-limit warnings): https://github.com/s0/changesets-action/actions/runs/10558945878/job/29249383365
> Switch to pull request list API instead of search

- .changeset/breezy-garlics-bathe.md
- src/index.ts
Prior to this PR it would tell you `No changesets found` if you omitted the `publish` script, and it was very hard to figure out what to do. It was also misleading as the only reason there were no changesets present is because they were deleted earlier in the release process
> Improve error message when attempting to publish without publish script defined

- src/index.ts
- src/run.ts
Update double negative variable for readability, and we don't use repo variable as we directly send `github.context.repo.repo` to octokit
> update: change double negative variable and remove unused variable

- .changeset/quiet-jeans-poke.md
- src/run.ts
Seems this pre-starting of request manages to time out in cases where there are a lot of changesets.
This can happen intermittently and sometimes seemingly randomly as sometimes code before last "await" will run slightly faster or slower
Possibly fixes all or many of those intermittent, large number of changesets or unknown error issues
> Do not pre-start github API request

- .changeset/dry-bugs-applaud.md
- package.json
- yarn.lock
Fixes the issue with`commitMode: github-api` in monorepos.
Closes #469
> Bump @changesets/ghcommit to v1.4.0

- .changeset/itchy-eyes-look.md
- src/git.ts
- src/index.ts
- src/run.ts
This is a follow-up from #471
Currently, depending on your `commitMode`, when running the action with `cwd` set to a subdirectory of a repo, the action will either:
- `git-cli`: add the files changed in the subdirectory only
- `github-api`: add files changed anywhere in the repository
This commit brings github-api in line with git-cli, so that it only adds files in the current working directory.
Related: https://github.com/changesets/ghcommit/issues/29
> Make git add work consistently with subdirectories

- .changeset/big-cougars-mate.md
- src/run.ts
There was a race-condition that means sometimes existing PRs would not be found, and new PRs would be opened. This has now been fixed by fetching existing PRs before making any changes.
fixes #487
> Fix PRs sometimes not getting reopened

- .changeset/lemon-garlics-sell.md
- .changeset/sour-elephants-switch.md
- package.json
- src/git.ts
- src/index.ts
- yarn.lock
- `cwd` was not working correctly when commitMode was set to `git-cli`, as it was attempting to resolve the `cwd` twice. (This problem only occured when specifying a relative path for `cwd`.)
- Update `ghcommit`, and avoid calling `process.chdir()` to change the working directory. Instead, we now pass the `cwd` option everywhere.
fixes #475
> fix: use latest ghcommit and fix cwd for git-cli
